### PR TITLE
Add screenshots of example documentation

### PR DESCRIPTION
**Pull request by 36degrees**
😍

### CODE REVIEW

**Comment by mcmillan** [comment]
Do we need the desktop / mobile screenshots if they're not referenced anywhere?

**Comment by 36degrees** [comment]
Arguably not. I thought it'd be worth including them in case they were useful to people in the future. If that's the case though it'd probably make sense to link to them from the README?

**Comment by mcmillan** [comment]
Let's just leave them there and not link to them from the README – I don't think it makes sense to link them for the hell of it.

**Comment by 36degrees** [comment]
👍

**Pull request merged**
