### PR TITLE
Fail build if there are dead internal links

### LINKED ISSUE #186: Add linter to check for dead links?
We're using this template for our technical documentation in GOV.UK Verify. One of the things we've found is that we slowly accumulated dead internal links due to content getting moved around.

To fix this, we've added a linter to catch new internal dead links, using [html-proofer](https://github.com/gjtorikian/html-proofer). It means that our docs will now not build if we introduce a new internal dead link.

Might this be something that would be useful to contribute upstream to the template?

### PR DESCRIPTION
**Pull request by bjgill**
Using html-proofer. Will apply to new projects only - existing users of the template would need to apply this change manually.

Resolves #186

### CODE REVIEW

**Comment by bjgill** [comment]
Interesting. It turns out it catches other problems as well. The build's just about to fail.

```
- build/index.html
  *  image /images/gov.uk_logotype_crown_invert_trans.png does not have an alt attribute (line 42)
HTML-Proofer found 1 failure!
```

I don't really know enough about HTML to know if this is a serious problem, however.

I guess this is possibly a question for the maintainers of the template, who might have opinions. [Here](https://github.com/gjtorikian/html-proofer#whats-tested) is the list of all the things that `html-proofer` checks. What do we actually want to check? I'm tempted to say everything - it's fairly simple for users to disable individual lints that do not make sense for them.

> ### Images
> 
> `img` elements:
> 
> * Whether all your images have alt tags
> * Whether your internal image references are not broken
> * Whether external images are showing
> * Whether your images are HTTP
> 
> ### Links
> 
> `a`, `link` elements:
> 
> * Whether your internal links are working
> * Whether your internal hash references (`#linkToMe`) are working
> * Whether external links are working
> * Whether your links are HTTPS
> * Whether CORS/SRI is enabled
> 
> ### Scripts
> 
> `script` elements:
> 
> * Whether your internal script references are working
> * Whether external scripts are loading
> * Whether CORS/SRI is enabled
> 
> ### Favicon
> 
> * Whether your favicons are valid.
> 
> ### OpenGraph
> 
> * Whether the images and URLs in the OpenGraph metadata are valid.
> 
> ### HTML
> 
> * Whether your HTML markup is valid. This is done via [Nokogiri](http://www.nokogiri.org/tutorials/ensuring_well_formed_markup.html) to ensure well-formed markup.
>

**Comment by bravegrape** [comment]
Thanks for raising this PR @bjgill 👍 We'll have a closer look at what exactly `html-proofer` checks for and see how to align that with the style guide and best practice.

**Comment by nickcolley** [comment]
This feature looks really useful.

One thing to consider is if this feature be proposed on the tech-docs-gem? Then it could be distributed as part of that gem.

If there's no activity on this for a while we'll close this out, to tidy things up, so let us know if you want to continue working on this. :+1:

**Comment by nickcolley** [comment]
I think it would be good to keep trying this approach in a few more of the important tech docs instances, for example the GaaP projects.

Then, when we're confident it works across different scenarios we could consider adding this to the gem itself?

**Comment by jonathanglassman** [comment]
> I think it would be good to keep trying this approach in a few more of the important tech docs instances, for example the GaaP projects.
> 
> Then, when we're confident it works across different scenarios we could consider adding this to the gem itself?

Seems sensible.

**Comment by bravegrape** [comment]
> I think it would be good to keep trying this approach in a few more of the important tech docs instances, for example the GaaP projects.
> 
> Then, when we're confident it works across different scenarios we could consider adding this to the gem itself?

Yup, sounds sensible, but worth mentioning that some docs, like the [PaaS docs have implemented link checking in other ways](https://github.com/alphagov/paas-tech-docs/blob/master/requirements.txt).

Might be one to try for the Pay docs @m-green ?

**Comment by m-green** [comment]
Definitely @bravegrape - was literally just trying this out locally on Pay docs after seeing this PR :)

**Comment by lfdebrux** [comment]
Closing this until we're ready to pick up #186 again.

**Pull request closed without merging**
